CHANGES.rst
MANIFEST.in
README.rst
RELEASE-NOTES.rst
docs/conf.py
setup.py
tests/test_record.py

Invenio-Records v0.1.0

---

invenio_records/providers/__init__.py
invenio_records/providers/recid.py
invenio_records/recordext/functions/reserve_recid.py
invenio_records/tasks/__init__.py
invenio_records/tasks/datacite.py
tests/test_tasks_datacite.py

* pidstore: code style improvements
* search: initial Elastic Search support
* pidstore: new pid provider for record identifiers

pidstore: port of recid provider and datacite tasks

---

invenio_records/providers/recid.py
invenio_records/recordext/functions/reserve_recid.py
invenio_records/tasks/datacite.py
setup.py
tests/test_tasks_datacite.py

--
depends on https://github.com/inveniosoftware/invenio-pidstore/issues/2

global: fix Invenio-PIDStore dependency

---

CHANGES.rst
RELEASE-NOTES.rst
setup.cfg
setup.py

Invenio-Records v0.2.0

---

invenio_records/upgrades/records_2014_04_14_json_type_fix.py
invenio_records/upgrades/records_2014_08_22_create_record_json.py

Signed-off-by: Eamonn Maguire <eamonnmag@gmail.com>

upgrader: fixed import to use invenio_upgrader

---

AUTHORS.rst
CHANGES.rst
MANIFEST.in
RELEASE-NOTES.rst
invenio_records/translations/de/LC_MESSAGES/messages.po
invenio_records/translations/es/LC_MESSAGES/messages.po
invenio_records/translations/fr/LC_MESSAGES/messages.po
invenio_records/translations/invenio.pot
invenio_records/translations/it/LC_MESSAGES/messages.po
invenio_records/version.py
setup.cfg

Invenio-Records v0.3.1

---

invenio_records/views.py

* INCOMPATIBLE Removes dependency on legacy bibdocfile module.
(addresses inveniosoftware/invenio#3233)

global: bibdocfile dependency removal

---

.travis.invenio.cfg
.travis.yml
CHANGES.rst
RELEASE-NOTES.rst
invenio_records/version.py
setup.py

Invenio-Records v0.3.2

---

invenio_records/api.py
invenio_records/registry.py
setup.py

* FIX Removes dependency on JSONAlchemy from Invenio package.

global: addition of functions registry

---

invenio_records/utils.py
invenio_records/views.py
setup.cfg

* INCOMPATIBLE Removes legacy bibrecord dependency.
(addresses inveniosoftware/invenio#3233) (closes #18)
(addresses inveniosoftware/invenio#3508)
* fix wheel setup configuration.

global: bibrecord dependency removal

---

invenio_records/tasks/datacite.py
requirements-devel.txt
setup.py

global: fix invenio_celery imports

---

invenio_records/receivers.py
invenio_records/tasks/api.py

Signed-off-by: Esteban J. G. Gabancho <esteban.gabancho@gmail.com>

global: missing imports fix

---

.travis.invenio.cfg
invenio_records/models.py
requirements-devel.txt
setup.py

* FIX Adds missing dependency to mock>=1.0.0.
* Updates PACKAGES in .travis.invenio.cfg to include all used
Invenio modules.
closes #9 

installation: dependency changes

---

setup.py

* Adds entry point for Invenio-Base to discover the Flask extension.

installation: entry point addition

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records/version.py

Invenio-Records v1.0.0a4

---

invenio_records/permissions.py
setup.py
tests/conftest.py
tests/test_invenio_records.py
tests/test_permissions.py

* NEW Adds default permission object for records.

WIP permissions: optional access control for records

---

invenio_records/api.py
invenio_records/ext.py
setup.py
tests/test_invenio_records.py

* Uses `jsonresolver` to retrieve remote referenced JSONSchemas.

global: resolver for JSONSchema validation

---

setup.py

* Fixes failing test case due to problem in Invenio-Accounts.

tests: failing tests temporary fix

---

invenio_records/permissions.py
setup.py
tests/test_permissions.py

* Adds test cases for records permissions. (closes #73)
* Changes action naming to be consistent with package name.

tests: record permission tests addition

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records/permissions.py
invenio_records/version.py
setup.py
tests/test_permissions.py

release: v1.0.0a5

---

docs/api.rst
invenio_records/ext.py
invenio_records/permissions.py
invenio_records/signals.py
invenio_records/tasks/api.py

* Ensures Sphinx includes API documentation.
* Removes record-viewed signal which is now in Invenio-Records-UI.

docs: api documentation inclusion

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records/version.py

release: v1.0.0a6

---

invenio_records/version.py

version: post-release bump

---

invenio_records/permissions.py
tests/test_permissions.py

* Adds permission classes and factories for writing one or all
records.
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>

permissions: write permissions addition

---

setup.py

i18n: entry point name fix

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records/admin.py
invenio_records/tasks/api.py
invenio_records/version.py
setup.py
tests/test_admin.py

* Adds simple low-level administration interface for records.

admin: records admin view + release v1.0.0a7

---

setup.py

* Adds missing `mock` test requirement.

installation: mock test requirement

---

.gitignore
INSTALL.rst
docs/usage.rst
examples/app.py

* FIX Amends the standalone example application to reflect record model
changes.
* BETTER Completes the installation and usage documentation.
* Adds SQLite test database to the git ignore list.

docs: better standalone example application

---

.editorconfig
invenio_records/api.py
invenio_records/ext.py
invenio_records/models.py
invenio_records/permissions.py
invenio_records/upgrades/records_2014_04_14_json_type_fix.py
invenio_records/upgrades/records_2014_08_22_create_record_json.py
requirements.py
setup.py
tests/demo/json_resolver.py
tests/test_api.py
tests/test_permissions.py

* Added JsonRefs' replace_refs method to Record API
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>

global: addition of replace_refs to record

---

AUTHORS.rst

docs: AUTHORS update

---

tests/demo/json_resolver.py
tests/test_api.py

* Unit test for nested JSONs resolving
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>

testing: nested json test

---

setup.py
tests/test_example_app.py

* BETTER Adds new `test_example_app.sh` script that tests provided
minimal standalone example application used in the documentation.
Helps to make sure that the documentation is up to date.

tests: new script to test example application

---

invenio_records/cli.py
invenio_records/models.py
setup.py

* Uses versioning support from Invenio-DB.
--

installation: usage of invenio-db[versioning]

---

invenio_records/api.py

@tiborsimko it should solve an issue with importing record models before the versioning is enabled (see https://github.com/inveniosoftware/invenio-records-ui/pull/24/files#diff-874df88d3090caff6f568b76f7518372R58).

api: fix global import of models

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records/version.py

Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>

release: v1.0.0a9

---

invenio_records/data/marc21/bibliographic.xml

data: control_number addition

---

examples/app.py
invenio_records/cli.py
invenio_records/data/marc21/bibliographic.xml
setup.py
tests/conftest.py
tests/test_invenio_records.py

* NEW Adds option to specify PID minters during record creation if Invenio-PIDStore package is installed.
--
- cc @tiborsimko @lnielsen @switowski @hachreak

cli: PID minter option

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records/version.py

release: v1.0.0a11

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records/version.py

release: v1.0.0a12

---

invenio_records/api.py
invenio_records/models.py
run-tests.sh
setup.cfg
setup.py
tests/test_api.py

* NEW Record now has get_records method for fetching multiple records.

api: bulk fetching for records

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records/version.py

release: v1.0.0a13

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records/version.py

release: v1.0.0a15

---

invenio_records/api.py

api: skip schema validation when None

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records/version.py

release: v1.0.0a16

---

setup.py

installation: pytest-runner in setup_requires

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records/version.py
setup.py
tests/test_example_app.py

release: v1.0.0a17

---

docs/conf.py
invenio_records/api.py

* Allows usage of custom jsonschema validation class. (addresses ##146)
cc @jirikuncar @lnielsen

api: custom jsonschema valitation

---

.tx/config
examples/app.py
invenio_records/cli.py
invenio_records/translations/cs/LC_MESSAGES/messages.po
invenio_records/translations/da/LC_MESSAGES/messages.po
invenio_records/translations/de/LC_MESSAGES/messages.po
invenio_records/translations/fr/LC_MESSAGES/messages.po
invenio_records/translations/it/LC_MESSAGES/messages.po
invenio_records/translations/messages.pot
setup.py
tests/conftest.py
tests/test_invenio_records.py

Signed-off-by: Alizee Pace <alizee.pace@gmail.com>

i18n: tx config fix and translation improvements

---

MANIFEST.in
README.rst
RELEASE-NOTES.rst
docs/requirements.txt
docs/usage.rst
requirements.py

docs: ReadTheDocs configuration

---

docs/requirements.txt

@tiborsimko this typo was probably causing the same issue we had yesterday :(

docs: ReadTheDocs configuration fix

---

invenio_records/alembic/1095cdf9f350_create_records_branch.py
invenio_records/alembic/862037093962_create_records_tables.py
setup.py
tests/test_invenio_records.py

Depends on inveniosoftware/invenio-db#59

global: initial alembic recipes

---

.editorconfig
.gitignore
.tx/config
CONTRIBUTING.rst
MANIFEST.in
docs/Makefile
docs/conf.py
docs/make.bat
docs/usage.rst
invenio_records/validators.py
setup.py

* FIX Adds changes according to release preparation checklist.
Signed-off-by: Paulina Lach <paulina.malgorzata.lach@cern.ch>

global: release checklist

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records/version.py

release: v1.0.0b2

---

invenio_records/api.py

* Sends signals always connected to the current app. (closes #165)
Signed-off-by: Jose Benito Gonzalez Lopez <jose.benito.gonzalez@cern.ch>

api: signals connected to an app

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records/version.py

Signed-off-by: Harris Tzovanakis <me@drjova.com>

release: v1.0.0b3

---

CHANGES.rst
invenio_records/version.py

release: v1.0.0b4

---

invenio_records/cli.py

cli: add deprecation warning

---

invenio_records/api.py
tests/test_api.py

*Fixes revisions resolving when there are gaps in revisions numbers
*INSPIR-3486

api: fix revisions resolving

---

invenio_records/api.py
invenio_records/dumpers/base.py
invenio_records/dumpers/elasticsearch.py
invenio_records/extensions.py
invenio_records/systemfields/base.py
invenio_records/systemfields/relatedmodelfield.py
invenio_records/version.py
tests/test_systemfields.py

closes inveniosoftware/invenio-drafts-resources#104

api: add pre-create hook

---

invenio_records/systemfields/base.py

Closes inveniosoftware/invenio-app-rdm#667.

systemfields: add post_dump and pre_load

---

invenio_records/api.py

closes https://github.com/inveniosoftware/invenio-records-resources/issues/243

record: do not mutate original data on loads

---

invenio_records/version.py
setup.py

closes #257 
release commit included

dependencies: restrict jsonschemas to lower than 4.0.0

---

invenio_records/systemfields/relations/relations.py
invenio_records/systemfields/relations/results.py
tests/test_relations_systemfield.py

* Adds vocabulary field to be able to
dereference one value from an object
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/695

system fields: relations

---

invenio_records/systemfields/relations/__init__.py
invenio_records/systemfields/relations/relations.py
invenio_records/systemfields/relations/results.py
tests/test_relations_systemfield.py

closes https://github.com/inveniosoftware/invenio-records-resources/issues/270

systemfields: add support for nested list relations

---

invenio_records/systemfields/relations/errors.py
invenio_records/systemfields/relations/relations.py
invenio_records/systemfields/relations/results.py
tests/test_relations_systemfield.py

* Adds check_value that will check if the value
provided matches the on retrieved
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/760

systemfields: add check_value for relation fields

---

invenio_records/systemfields/relations/results.py
tests/test_relations_systemfield.py

* closes https://github.com/inveniosoftware/invenio-records/issues/266

relations: Update value_check to accept lists

---

invenio_records/systemfields/relations/__init__.py
invenio_records/version.py

* closes https://github.com/inveniosoftware/invenio-records-resources/issues/280

relations: export missing error

---

CHANGES.rst
LICENSE
invenio_records/api.py
invenio_records/extensions.py
invenio_records/systemfields/base.py
invenio_records/version.py
setup.py
tests/test_systemfields.py

As discussed on Discord (https://discord.com/channels/692989811736182844/724974365451747329/844554342613778452)

api: add post-commit hook

---

.github/workflows/tests.yml
invenio_records/api.py
invenio_records/validators.py
setup.py

docstrings: fix jsonschema.IValidator references

Fix broken build

---

invenio_records/translations/de/LC_MESSAGES/messages.po

* add german translations
related inveniosoftware/invenio-app-rdm/issues/1664

i18n: adds german translations

---

invenio_records/systemfields/relations/__init__.py
invenio_records/systemfields/relations/field.py

Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1003

systemfields: add multi relations field

---

invenio_records/systemfields/relations/field.py

Needs to be lazy loaded due to:
- This field is added to `relations` <[inveniosoftware/invenio-rdm-records#1021](https://github.com/inveniosoftware/invenio-rdm-records/pull/1021/files#diff-5d1307e2e4f0dc8f18dff697e272b141a20ce79d1017b2f7771c51740123beeeR208>), since it is a class attr it will be initialized before app context.
- This will initialize the field here https://github.com/inveniosoftware/invenio-vocabularies/blob/master/invenio_vocabularies/records/systemfields/relations.py#L31 (I know it's lazy there buuuut....)
- here it gets called https://github.com/inveniosoftware/invenio-records/blob/master/invenio_records/systemfields/relations/field.py#L130 which happens on initialization of the field. So even if at vocabularies level is lazy, invenio-records does the call.
NOTE: I do …

relations: lazy loading for MultiRelationsField _fields

---

invenio_records/admin.py

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2162

translations: fix string format

---

.github/workflows/tests.yml
invenio_records/dumpers/search.py
tests/test_invenio_records.py

* closes https://github.com/zenodo/zenodo-rdm/issues/590

search: prevent flush on search queries

---

CHANGES.rst
invenio_records/__init__.py
invenio_records/api.py

* the thinking of handling negative revision numbers in this line with
the list was wrong

fix: the correct handling is done in the iterator

---

setup.cfg

:heart: Thank you for your contribution!
> Please describe briefly your pull request.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the …

I18n-fix-setuptools-backport
