inveniosoftware/invenio-records

invenio_records/config.py, invenio_records/manage.py, tests/data/sample-records.xml, tests/test_processors.py
* Adds new config variable RECORD_PROCESSORS that allows to
specify what processors to use depending on the input type.
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>
=> global: processors configuration

invenio_records/access.py, invenio_records/api.py, invenio_records/config.py, invenio_records/views.py
When accessing any record:
```
17:30:37 web.1       | --------------------------------------------------------------------------------
17:30:37 web.1       | Traceback (most recent call last):
17:30:37 web.1       |   File "/Users/egabancho/Work/envs/cdslabs/src/invenio/invenio/ext/legacy/__init__.py", line 107, in __call__
17:30:37 web.1       |     response = self.app.full_dispatch_request()
17:30:37 web.1       |   File "/Users/egabancho/Work/envs/cdslabs/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
17:30:37 web.1       |     rv = self.handle_user_exception(e)
17:30:37 web.1       |   File "/Users/egabancho/Work/envs/cdslabs/lib/python2.7/site-packages/flask_restful/__init__.py", line 270, in error_router
17:30:37 web.1       |     return …
```
=> access: user rights check fix

invenio_records/views.py
* FIX Fixes export of records in non HTML formats.
(closes inveniosoftware/invenio#3351)
=> views: fix export of non HTML formats

invenio_records/api.py
* FIX Loads all recordext functions registered before
updating a record via `Record.commit()`.
Signed-off-by: Jan Aage Lavik <jan.age.lavik@cern.ch>
=> api: record update fix

AUTHORS.rst, invenio_records/access.py, requirements-devel.txt, setup.py
* Adds missing `invenio_access` dependency and amends past upgrade
recipes following its separation into standalone package.
=> installation: fix invenio_access imports

invenio_records/api.py
* FIX Disables autoflush when pulling records out of the databse, to
prevent superfluous call to `flush()`. (closes #24)
Signed-off-by: Dimitrios Semitsoglou-Tsiapos <dsemitso@cern.ch>
=> api: fix autoflush on get_record

.travis.invenio.cfg, invenio_records/access.py, invenio_records/api.py, invenio_records/manage.py, invenio_records/tasks/datacite.py, invenio_records/utils.py, invenio_records/views.py, requirements-devel.txt, setup.py
* FIX Adds missing `invenio_base` dependency and amends past
upgrade recipes following its separation into standalone package.
=> installation: fix invenio_base imports

invenio_records/signals.py
* FIX Fixes definition of after_record_insert and after_record_update
signals, which wrongly referred to their before- counterparts.
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>
=> signals: signal definition fix

invenio_records/tasks/__init__.py
* Removes imports from tasks submodule init.py. (closes #59)
=> tasks: removal of submodule init imports

invenio_records/api.py, invenio_records/cli.py, invenio_records/errors.py, invenio_records/models.py, invenio_records/tasks/api.py, tests/test_invenio_records.py
More PRs in the pipeline, so don't merge until the complete picture is there.
* INCOMPATIBLE Changes primary key of records to UUIDType instead of
auto-incrementing integers.
* INCOMPATIBLE Removes functional interface to records.
* INCOMPATIBLE Renames SQLAlchemy model from Record to RecordMetadata
to avoid naming confusion with API Record class.
* FIX Fixes typo in configuration variables.
=> global: uuid record identifier

invenio_records/api.py, invenio_records/errors.py, invenio_records/signals.py, tests/conftest.py, tests/test_api.py, tests/test_invenio_records.py
* NEW Adds support for retrieving past revisions of a record as well
as reverting a record to a past revision. (closes #10)
* NEW Adds support for deleting records. (closes #64)
* BETTER Adds support in API for accessing a records revision id and
creation/modification timestamps.
=> api: revision and delete support

examples/app.py, invenio_records/cli.py, tests/test_invenio_records.py
* Removes usage of Celery for creating records using CLI.
* Accepts record UUIDs.
=> cli: record creation without celery

invenio_records/api.py, tests/test_api.py
It seems that it's not so easy to update an iterable key within the record:
Is this:
```
rec['some_iterable'].append('foo_item')
```
unsupported in favour of:
```
rec['some_iterable'] = rec['some_iterable'] + ['foo_item', ]
```
?
=> api: fix appending to iterable in JSON

invenio_records/config.py, invenio_records/ext.py, tests/test_invenio_records.py
* NEW Adds support for passing additional validation types when
validating records with `jsonschema` via `RECORDS_VALIDATION_TYPES`
configuration variable. For example, to allow `array`
type to be `list` and `tuple` instead of `list` only.
Signed-off-by: Jan Aage Lavik <jan.age.lavik@cern.ch>
=> config: additional validation types

docs/conf.py, invenio_records/api.py, tests/test_api.py
* Record.dumps method returns a deep-copied dictionary.
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
=> api: record dump fix

invenio_records/data/marc21/bibliographic.xml
* FIX Amends demo file containing MARC bibliographic records in order to
remove repetitive affiliations in author fields. This is not allowed
by the MARC21 standard and was preventing the population of the
Invenio demo site.
=> data: affiliation fix in MARC bibliographic

docs/api.rst, invenio_records/api.py, setup.py
* Improves documentation. (addresses #140)
=> docs: addition of param and result sections

AUTHORS.rst, docs/conf.py, invenio_records/api.py, invenio_records/ext.py, tests/test_api.py
* Makes the FormatChecker feature of jsonschema accessible by allowing
arbitrary keyword arguments in calls to validate and create, which
are passed to the underlying jsonschema implementation (closes #142).
* Adds a reminder about this jsonschema feature in the documentation,
and a complete example as a test.
Signed-off-by: Jacopo Notarstefano <jacopo.notarstefano@cern.ch>
=> api: addition of FormatChecker support

AUTHORS.rst, docs/index.rst
* Fixes typo in index.rst that addresses the module as Invenio-Base
instead of Invenio-Records.
Signed-off-by: Orestis Melkonian <melkon.or@gmail.com>
=> docs: index.rst typo fix

examples/app.py
* Fixes the debugging instructions in examples/app.py (closes #151)
Signed-off-by: Diego Rodriguez Rodriguez <diego.rodriguez.rodriguez@cern.ch>
=> docs: debugging instructions fix

invenio_records/api.py, tests/test_api.py
* Allows usage of custom jsonschema validation class when
using Record.commit. (closes #162)
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
=>  api: custom jsonschema valitation for commit

invenio_records/api.py, invenio_records/validators.py, tests/test_api.py
* Adds a new special validator that contains the same validation
rules of Draft4Validator, except for required fields.
=> validators: partial validator addition

.travis.yml, invenio_records/admin.py, invenio_records/models.py, setup.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
=> travis: fix mysql fractional seconds

invenio_records/cli.py, tests/test_invenio_records.py
* FIX Allows to fully delete a record that was already soft-deleted.
(closes #173)
Signed-off-by: Jose Benito Gonzalez Lopez <jose.benito.gonzalez@cern.ch>
=> cli: full deletion of soft-deleted records

invenio_records/data/marc21/bibliographic.xml
* Fixes MARC indicator for two example records. (closes #169)
Signed-off-by: Jose Benito Gonzalez Lopez <jose.benito.gonzalez@cern.ch>
=> global: bibliographic demo records with wrong marc

tests/test_invenio_records.py
* Changes the expected exit_code to 1, for compatibility
with click>=7.0.
Relevant issue:
https://github.com/inveniosoftware/troubleshooting/issues/41
Closes #198 
Signed-off-by: Dinos Kousidis <dinos.kousidis@cern.ch>
=> tests: fix exit_code for CliRunner exceptions

invenio_records/api.py, invenio_records/cli.py, invenio_records/models.py, setup.py, tests/conftest.py, tests/test_api.py, tests/test_invenio_records.py
* closes: #191
Signed-off-by: Johnny Mariéthoz <johnny.mariethoz@rero.ch>
=> api: addition of class model support

CHANGES.rst, invenio_records/version.py, setup.py
* Specifies "werkzeug>0.14.1" in "install_required" in order for
"requirements-builder" to install the correct version. (closes #209)
=> installation: relax Flask version to 0.11.1

invenio_records/dumpers/elasticsearch.py, invenio_records/systemfields/model.py, tests/test_api_dumpers.py
* The @ prefix was used to separate metadata fields from other fields,
however it wasn't used consistently, and using it will make it harder
(though not impossible) to later use e.g. Elasticsearch DSL Document
class for defining indexes.
=> dumpers: remove @-prefix from model fields

invenio_records/systemfields/__init__.py, invenio_records/systemfields/relatedmodelfield.py, invenio_records/version.py, run-tests.sh, setup.py, tests/conftest.py, tests/test_admin.py, tests/test_systemfields_relatedmodelfield.py
* Adds a related model field which helps serialize/deserialize a related
object to/from the record dictionary. The core is extract from the
PIDField in Invenio-Records-Resources. (closes #246)
=> systemfields: adds a related model field

invenio_records/config.py, invenio_records/errors.py, invenio_records/ext.py, invenio_records/resolver.py, setup.py, tests/test_resolver.py
Closes inveniosoftware/invenio-rdm-records#356.
**Progress**:
An integration test can be run locally:
- At Invenio-RDM-Records level: https://github.com/inveniosoftware/invenio-rdm-records/pull/492
=> ext: configurable local ref resolver store

invenio_records/systemfields/model.py
closes https://github.com/inveniosoftware/invenio-records/issues/277
support for dict access to a `record[model_field_name]`
=> systemfields: initialize model parent

invenio_records/dumpers/indexedat.py, setup.py, tests/test_api_dumpers.py
- closes https://github.com/inveniosoftware/invenio-records/issues/278
@slint Tests are failing beacuase of `LocalStack` (i.e. Flask 2.1 integration). If the PR changes are approved, I will fix the tests before merging.
=> dumpers: add indexed time

invenio_records/systemfields/relations/results.py
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1358
- Fixed an issue where non-existent attributes would raise a `KeyError` when dereferencing. This would prevent the rest of the attributes from being dereferenced. 
`dict_lookup` raises an exception, does not return `None`, if not found. In addition, it does not accept a default value. Therefore, we need to `try/except`.
=> systemfields: fixed dereferencing for unexisting attrs

invenio_records/dumpers/base.py
:heart: Thank you for your contribution!
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
=> dumpers: revert dict merging of dumps

.github/workflows/tests.yml, CHANGES.rst, invenio_records/__init__.py, invenio_records/systemfields/relations/results.py, invenio_records/validators.py, tests/test_relations_systemfield.py
:heart: Thank you for your contribution!
Closes Issue https://github.com/inveniosoftware/invenio-vocabularies/issues/403
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree …
=> relation: modified lookup_data for nested fields & 📦 release: v2.4.0

.github/workflows/pypi-publish.yml, CHANGES.rst, docs/conf.py, invenio_records/__init__.py, invenio_records/api.py, setup.cfg
- setup: bump major dependencies
- release: v3.0.0
=> bump major

invenio_records/admin.py
This pull request fixes premature evaluation of i18n strings inside static fields. gettext call, that causes
the evaluation to be performed at boot time, was replaced with gettext_lazy that is performed at
request time. This fixes column labels in administration not being translated when language is changed.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …
=> Using lazy_gettext in boot-time translations

CHANGES.rst, invenio_records/__init__.py
:heart: Thank you for your contribution!
> Please describe briefly your pull request.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the …
=> Release-2.5.0
